# Generated by Django 4.1.1 on 2022-11-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectarea',
            name='type',
        ),
    ]
