# Generated by Django 4.1.1 on 2022-11-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alaapp', '0002_assignment_criteria_day_scoring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameelement',
            name='user_completes',
        ),
    ]
