# Generated by Django 4.1.1 on 2022-11-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alaapp', '0002_remove_projectarea_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubarea',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
