# Generated by Django 4.1.1 on 2022-11-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alaapp', '0003_projectsubarea_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='like_dislike',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
