# Generated by Django 4.1.1 on 2022-12-06 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alaapp', '0004_alter_checkin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameelement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alaapp.user'),
        ),
    ]
