# Generated by Django 4.1.1 on 2022-11-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alaapp', '0004_progress_like_dislike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progress',
            new_name='Assignment',
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignment'},
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='assignment',
        ),
    ]
