# Generated by Django 4.1.1 on 2022-11-23 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alaapp', '0005_rename_progress_assignment_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Criteria',
                'verbose_name_plural': 'Criterias',
                'db_table': 'criteria',
            },
        ),
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.IntegerField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alaapp.assignment')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alaapp.criteria')),
            ],
            options={
                'verbose_name': 'Scoring',
                'verbose_name_plural': 'Scorings',
                'db_table': 'scoring',
            },
        ),
    ]
