# Generated by Django 4.1.1 on 2022-11-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alaapp', '0006_criteria_scoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
                'db_table': 'day',
            },
        ),
    ]
