# Generated by Django 4.1.1 on 2022-11-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alaapp', '0007_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerestriction',
            name='days',
            field=models.ManyToManyField(to='alaapp.day'),
        ),
        migrations.AddField(
            model_name='timerestriction',
            name='hour_from',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timerestriction',
            name='hour_to',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
