# Generated by Django 4.1.1 on 2022-11-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alaapp', '0008_timerestriction_days_timerestriction_hour_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerestriction',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
