# Generated by Django 4.1.1 on 2022-09-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complete_name", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("role_id", models.IntegerField()),
            ],
        ),
    ]
