# Generated by Django 4.1.1 on 2022-09-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
