# Generated by Django 4.1.1 on 2022-09-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0002_user_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=0),
        ),
    ]
