# Generated by Django 4.1.1 on 2022-10-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0003_alter_user_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="role_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="creativescienceapp.role",
            ),
        ),
        migrations.AlterModelTable(
            name="role",
            table="role",
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
