# Generated by Django 4.1.1 on 2022-10-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0003_proyect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyect",
            name="image",
            field=models.ImageField(
                default="creativescience/creativescienceapp/static/proyect_image/rio.jpg",
                upload_to="creativescience/creativescienceapp/static/proyect_image/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                default="creativescience/creativescienceapp/static/profile_image/user.png",
                upload_to="creativescience/creativescienceapp/static/profile_image/",
            ),
        ),
    ]
