# Generated by Django 4.1.1 on 2022-10-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0004_alter_role_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image_profile",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
