# Generated by Django 4.1.1 on 2022-10-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0006_alter_user_image_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/profile_image"
            ),
        ),
    ]
