# Generated by Django 4.1.1 on 2022-10-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0007_alter_user_image_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image_profile",
            new_name="profile_image",
        ),
    ]
