# Generated by Django 4.1.1 on 2022-10-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0009_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="creativescienceapp/static/profile_image",
            ),
        ),
    ]
