# Generated by Django 4.1.1 on 2022-10-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "creativescienceapp",
            "0009_alter_badge_options_alter_challenge_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameelement",
            options={
                "verbose_name": "GameElement",
                "verbose_name_plural": "GameElements",
            },
        ),
        migrations.AlterModelTable(
            name="gameelement",
            table="game_element",
        ),
    ]
