# Generated by Django 4.1.1 on 2022-10-05 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0010_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="creativescienceapp.role",
            ),
        ),
    ]
