# Generated by Django 4.1.1 on 2022-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0014_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
