# Generated by Django 4.1.1 on 2022-10-08 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0016_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="creativescienceapp.role",
            ),
        ),
    ]
