# Generated by Django 4.1.1 on 2022-10-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0017_alter_user_role_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="creativescienceapp/static/profile_image/user.png",
                null=True,
                upload_to="creativescienceapp/static/profile_image/",
            ),
        ),
    ]
