# Generated by Django 4.1.1 on 2022-10-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creativescienceapp", "0018_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                default="creativescienceapp/static/profile_image/user.png",
                upload_to="creativescienceapp/static/profile_image/",
            ),
        ),
    ]
