# Generated by Django 4.1.1 on 2022-11-07 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=200)),
                ('long', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'areas',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(default='ludoscienceapp/static/proyect_image/rio.jpg', upload_to='ludoscienceapp/static/proyect_image/')),
                ('avaliable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Proyect',
                'verbose_name_plural': 'Proyects',
                'db_table': 'proyect',
            },
        ),
        migrations.CreateModel(
            name='ProyectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('polygon', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ProyectArea',
                'verbose_name_plural': 'ProyectAreas',
                'db_table': 'proyect_area',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='TimeRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date_from', models.DateField(blank=True, max_length=10, null=True)),
                ('date_to', models.DateField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'TimeRestriction',
                'verbose_name_plural': 'TimesRestrictions',
                'db_table': 'time_restriction',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(default='ludoscienceapp/static/profile_image/user.png', upload_to='ludoscienceapp/static/profile_image/')),
                ('verified', models.BooleanField(default=False)),
                ('proyects', models.ManyToManyField(related_name='proyects', to='ludoscienceapp.proyect')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.user')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'token',
            },
        ),
        migrations.AddField(
            model_name='proyect',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to='ludoscienceapp.user'),
        ),
        migrations.AddField(
            model_name='proyect',
            name='areas',
            field=models.ManyToManyField(to='ludoscienceapp.proyectarea'),
        ),
        migrations.AddField(
            model_name='proyect',
            name='time_restriction',
            field=models.ManyToManyField(to='ludoscienceapp.timerestriction'),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField()),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.proyect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.user')),
            ],
            options={
                'verbose_name': 'CheckIn',
                'verbose_name_plural': 'CheckIns',
                'db_table': 'check_in',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.proyectarea')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.user')),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.proyect')),
                ('time_restriction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.timerestriction')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': ' Challenges',
                'db_table': 'challenge',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(default='ludoscienceapp/static/game_elements_image/ge.jpg', upload_to='ludoscienceapp/static/game_elements_image/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.user')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.badge')),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.proyect')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'badge',
            },
        ),
    ]
