# Generated by Django 4.1.1 on 2022-11-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=200)),
                ('long', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'areas',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='ProyectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('polygon', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ProyectArea',
                'verbose_name_plural': 'ProyectAreas',
                'db_table': 'proyect_area',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='TimeRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dates', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'TimeRestriction',
                'verbose_name_plural': 'TimesRestrictions',
                'db_table': 'time_restriction',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(default='ludoscienceapp/static/profile_image/user.png', upload_to='ludoscienceapp/static/profile_image/')),
                ('verified', models.BooleanField(default=False)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.user')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'token',
            },
        ),
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(default='ludoscienceapp/static/proyect_image/rio.jpg', upload_to='ludoscienceapp/static/proyect_image/')),
                ('avaliable', models.BooleanField(default=False)),
                ('admins', models.ManyToManyField(to='ludoscienceapp.user')),
                ('areas', models.ManyToManyField(to='ludoscienceapp.proyectarea')),
                ('time_restriction', models.ManyToManyField(to='ludoscienceapp.timerestriction')),
            ],
            options={
                'verbose_name': 'Proyect',
                'verbose_name_plural': 'Proyects',
                'db_table': 'proyect',
            },
        ),
        migrations.CreateModel(
            name='GameElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.user')),
            ],
            options={
                'verbose_name': 'GameElement',
                'verbose_name_plural': 'GameElements',
                'db_table': 'game_element',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('gameelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ludoscienceapp.gameelement')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.proyectarea')),
                ('time_restriction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.timerestriction')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': ' Challenges',
                'db_table': 'challenge',
            },
            bases=('ludoscienceapp.gameelement',),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('gameelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ludoscienceapp.gameelement')),
                ('image', models.ImageField(default='ludoscienceapp/static/game_elements_image/ge.jpg', upload_to='ludoscienceapp/static/game_elements_image/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.badge')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'badge',
            },
            bases=('ludoscienceapp.gameelement',),
        ),
    ]
