# Generated by Django 4.1.1 on 2022-11-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.AddField(
            model_name='challenge',
            name='checkin',
            field=models.ManyToManyField(related_name='checkin', to='ludoscienceapp.checkin'),
        ),
    ]
