# Generated by Django 4.1.1 on 2022-11-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0002_delete_area_challenge_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectarea',
            name='polygon',
            field=models.TextField(),
        ),
    ]
