# Generated by Django 4.1.1 on 2022-10-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ludoscienceapp", "0002_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="ludoscience/static/proyect_image/rio.jpg",
                        upload_to="ludoscience/static/proyect_image/",
                    ),
                ),
                ("admins", models.ManyToManyField(to="ludoscienceapp.user")),
            ],
            options={
                "verbose_name": "Proyect",
                "verbose_name_plural": "Proyects",
                "db_table": "proyect",
            },
        ),
    ]
