# Generated by Django 4.1.1 on 2022-11-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0002_gameelement_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameelement',
            name='public',
            field=models.BooleanField(default=1),
        ),
    ]
