# Generated by Django 4.1.1 on 2022-11-09 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0003_alter_proyectarea_polygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='checkin',
        ),
        migrations.AddField(
            model_name='badge',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.proyectarea'),
        ),
        migrations.AddField(
            model_name='badge',
            name='checkin',
            field=models.ManyToManyField(related_name='checkins', to='ludoscienceapp.checkin'),
        ),
        migrations.AddField(
            model_name='badge',
            name='time_restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.timerestriction'),
        ),
    ]
