# Generated by Django 4.1.1 on 2022-11-17 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0003_alter_gameelement_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameelement',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.projectsubarea'),
        ),
    ]
