# Generated by Django 4.1.1 on 2022-11-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0004_gameelement_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameelement',
            name='proyect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.proyect'),
        ),
    ]
