# Generated by Django 4.1.1 on 2022-11-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0005_gameelement_proyect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameelement',
            name='proyect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.proyect'),
        ),
    ]
