# Generated by Django 4.1.1 on 2022-11-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0005_challenge_checkin_alter_badge_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='checkin',
            field=models.ManyToManyField(related_name='%(class)s_checkins', to='ludoscienceapp.checkin'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='checkin',
            field=models.ManyToManyField(related_name='%(class)s_checkins', to='ludoscienceapp.checkin'),
        ),
    ]
