# Generated by Django 4.1.1 on 2022-11-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0006_alter_badge_checkin_alter_challenge_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenges_actives',
            field=models.ManyToManyField(related_name='challenges_actives', to='ludoscienceapp.challenge'),
        ),
    ]
