# Generated by Django 4.1.1 on 2022-10-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ludoscienceapp", "0006_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyect",
            name="avaliable",
            field=models.BooleanField(default=False),
        ),
    ]
