# Generated by Django 4.1.1 on 2022-11-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0006_alter_gameelement_proyect'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='players',
            field=models.ManyToManyField(related_name='players', to='ludoscienceapp.user'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to='ludoscienceapp.user'),
        ),
    ]
