# Generated by Django 4.1.1 on 2022-11-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0007_user_challenges_actives'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenges_completes',
            field=models.ManyToManyField(related_name='challenges_completes', to='ludoscienceapp.challenge'),
        ),
    ]
