# Generated by Django 4.1.1 on 2022-11-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0007_proyect_players_alter_proyect_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyect',
            name='players',
        ),
        migrations.AddField(
            model_name='user',
            name='proyects',
            field=models.ManyToManyField(related_name='players', to='ludoscienceapp.proyect'),
        ),
    ]
