# Generated by Django 4.1.1 on 2022-10-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ludoscienceapp", "0008_gameelement_challenge_badge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={"verbose_name": "Badge", "verbose_name_plural": "Badges"},
        ),
        migrations.AlterModelOptions(
            name="challenge",
            options={"verbose_name": "Challenge", "verbose_name_plural": " Challenges"},
        ),
        migrations.AlterModelTable(
            name="badge",
            table="badge",
        ),
        migrations.AlterModelTable(
            name="challenge",
            table="challenge",
        ),
    ]
