# Generated by Django 4.1.1 on 2022-11-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0008_user_challenges_completes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'verbose_name': 'Challenge', 'verbose_name_plural': 'Challenges'},
        ),
        migrations.AddField(
            model_name='badge',
            name='user_actives',
            field=models.ManyToManyField(related_name='%(class)s_actives', to='ludoscienceapp.challenge'),
        ),
        migrations.AddField(
            model_name='badge',
            name='user_completes',
            field=models.ManyToManyField(related_name='%(class)s_completes', to='ludoscienceapp.challenge'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='user_actives',
            field=models.ManyToManyField(related_name='%(class)s_actives', to='ludoscienceapp.challenge'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='user_completes',
            field=models.ManyToManyField(related_name='%(class)s_completes', to='ludoscienceapp.challenge'),
        ),
    ]
