# Generated by Django 4.1.1 on 2022-11-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0008_remove_proyect_players_user_proyects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='proyects',
            field=models.ManyToManyField(related_name='proyects', to='ludoscienceapp.proyect'),
        ),
    ]
