# Generated by Django 4.1.1 on 2022-11-10 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0009_alter_challenge_options_badge_user_actives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='challenges_actives',
        ),
        migrations.RemoveField(
            model_name='user',
            name='challenges_completes',
        ),
    ]
