# Generated by Django 4.1.1 on 2022-10-25 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ludoscienceapp",
            "0010_alter_gameelement_options_alter_gameelement_table",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gameelement",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ludoscienceapp.user",
            ),
        ),
    ]
