# Generated by Django 4.1.1 on 2022-11-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0010_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerestriction',
            name='dates',
        ),
        migrations.AddField(
            model_name='timerestriction',
            name='date_from',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timerestriction',
            name='date_to',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timerestriction',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
