# Generated by Django 4.1.1 on 2022-11-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0010_remove_user_challenges_actives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='user_actives',
            field=models.ManyToManyField(related_name='%(class)s_actives', to='ludoscienceapp.user'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='user_completes',
            field=models.ManyToManyField(related_name='%(class)s_completes', to='ludoscienceapp.user'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='user_actives',
            field=models.ManyToManyField(related_name='%(class)s_actives', to='ludoscienceapp.user'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='user_completes',
            field=models.ManyToManyField(related_name='%(class)s_completes', to='ludoscienceapp.user'),
        ),
    ]
