# Generated by Django 4.1.1 on 2022-11-10 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0011_alter_badge_user_actives_alter_badge_user_completes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='proyect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='ludoscienceapp.proyect'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='proyect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='ludoscienceapp.proyect'),
        ),
    ]
