# Generated by Django 4.1.1 on 2022-10-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ludoscienceapp", "0011_gameelement_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.CharField(max_length=200)),
                ("long", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "areas",
                "db_table": "area",
            },
        ),
        migrations.AlterField(
            model_name="gameelement",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ludoscienceapp.area",
            ),
        ),
    ]
