# Generated by Django 4.1.1 on 2022-11-12 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0012_alter_badge_proyect_alter_challenge_proyect'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.user')),
            ],
            options={
                'verbose_name': 'ChallengeProgress',
                'verbose_name_plural': 'ChallengesProgress',
                'db_table': 'challenge_progress',
            },
        ),
    ]
