# Generated by Django 4.1.1 on 2022-11-12 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0013_challengeprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ludoscienceapp.user')),
            ],
            options={
                'verbose_name': 'BadgeProgress',
                'verbose_name_plural': 'BadgesProgress',
                'db_table': 'badge_progress',
            },
        ),
    ]
