# Generated by Django 4.1.1 on 2022-10-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ludoscienceapp", "0013_gameelement_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameelement",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
