# Generated by Django 4.1.1 on 2022-10-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0014_alter_gameelement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(default='ludoscienceapp/static/game_elements_image/ge.jpg', upload_to='ludoscienceapp/static/game_elements_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='ludoscienceapp/static/profile_image/user.png', upload_to='ludoscienceapp/static/profile_image/'),
        ),
    ]
