# Generated by Django 4.1.1 on 2022-11-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0014_badgeprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeprogress',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
