# Generated by Django 4.1.1 on 2022-11-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0015_alter_challengeprogress_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeprogress',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
