# Generated by Django 4.1.1 on 2022-11-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0015_alter_badge_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='image',
            field=models.ImageField(default='ludoscienceapp/static/proyect_image/rio.jpg', upload_to='ludoscienceapp/static/proyect_image/'),
        ),
    ]
