# Generated by Django 4.1.1 on 2022-11-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0016_alter_badgeprogress_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectSubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_area', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludoscienceapp.proyectarea')),
            ],
            options={
                'verbose_name': 'ProyectSubArea',
                'verbose_name_plural': 'ProyectSubAreas',
                'db_table': 'proyect_subarea',
            },
        ),
    ]
