# Generated by Django 4.1.1 on 2022-11-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0017_proyectsubarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyect',
            name='areas',
        ),
        migrations.AddField(
            model_name='proyect',
            name='areas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ludoscienceapp.proyectarea'),
        ),
    ]
