# Generated by Django 4.1.1 on 2022-11-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0019_rename_areas_proyect_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectarea',
            old_name='polygon',
            new_name='type',
        ),
    ]
