# Generated by Django 4.1.1 on 2022-11-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoscienceapp', '0020_rename_polygon_proyectarea_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectsubarea',
            name='sub_area',
            field=models.TextField(max_length=800),
        ),
    ]
